In [1]:
!python --version
import numpy as np

print('NumPy', np.__version__)

Python 3.8.10
NumPy 1.22.4


In [2]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzz(x):
  if x%5==0 and x%3==0:
    answer ="FizzBuzz!"
  elif x%5 == 0:
    answer="Buzz!"
  elif x%3 == 0:
    answer="Fizz!"
  else:
    answer="..."
  return answer



In [3]:
print(FizzBuzz(3))
print(FizzBuzz(7))
print(FizzBuzz(5))
print(FizzBuzz(11))
print(FizzBuzz(15))

Fizz!
...
Buzz!
...
FizzBuzz!


In [4]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzzList(n):
  ans =[]
  for i in range (1,n+1):
    ans.append(FizzBuzz(i))

  return ans

In [5]:
print(FizzBuzzList(5))
print(FizzBuzzList(-30))

['...', '...', 'Fizz!', '...', 'Buzz!']
[]


In [6]:
import numpy as np

X = np.array([1.2,3.2,4.3,5.6])
print(X.mean())
print(X.std())

3.5749999999999997
1.6130328576938535


In [7]:

import numpy as np

def standarize(X):
  X_standarized = (( X - X.mean() )/ X.std())
  return X_standarized

In [8]:
##test
X0 = np.array([4.8, 4.0, 4.2, 4.0, 5.0])
standarize(X0)

array([ 0.95346259, -0.95346259, -0.47673129, -0.95346259,  1.43019388])

In [9]:
X1 = np.arange(5)
standarize(X1)

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [10]:
import numpy as np
A = np.array([
    [1, 0, 2, 9, 2],
    [9, 2, 6, 5, 7],
    [6, 4, 3, 4, 7]
    
])

print(A.astype(float))

print(np.diag(A))

print(np.diag(np.diag(A)))

[[1. 0. 2. 9. 2.]
 [9. 2. 6. 5. 7.]
 [6. 4. 3. 4. 7.]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [11]:
import numpy as np

def main_diagonal_matrix(A):
  D = np.diag(np.diag(A.astype(float)))
  return D


In [12]:
##test
A = np.array([
    [1, 0, 2, 9, 2],
    [9, 2, 6, 5, 7],
    [6, 4, 3, 4, 7]

])
main_diagonal_matrix(A)

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [13]:
A = np.array([
    [4, 0, 2],
    [9, 5, 6],
    [1, 9, 6],
    [3, 0, 5]

])
main_diagonal_matrix(A)

array([[4., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.]])